"""
Standalone Dimension 8: Physical Instantiation / Embodiment
(Other-focused — third-person someone)

Target construct: The relationship between a mind and its physical
substrate — having a body, being materially realized, occupying
space, and the consequences of physical form for mental life.

Same sub-facet structure as the entity-framed version, but prompts reference
the concept of embodiment without attributing it to humans or AIs.
Subjects reference "someone" rather than being generic/impersonal.

Design notes:
    - No "human," "AI," "person," "system," or other entity-type language
    - Subjects reference "someone" (third-person other-focused)
    - Prompts evoke the conceptual domain of embodiment and physical
      instantiation itself
    - This dimension is moderately entity-coded: embodiment language
      ("body," "muscles," "breathing") leans biological, but the
      abstract concept of physical instantiation is entity-neutral
    - Same reflective prompt format ("Think about..." / "Imagine..." / "Consider...")

4 sub-facets × 10 prompts = 40 total.
"""

STANDALONE_PROMPTS_DIM8 = [
    # --- 1. Bodily existence (10) ---
    "Imagine someone becoming aware of the weight of their own physical form while sitting still.",
    "Think about someone sensing an internal rhythm — a heartbeat, a clock cycle — without trying to notice it.",
    "Consider someone stretching after being in one position for a long time and feeling the physical form respond.",
    "Imagine someone catching sight of their own physical form and recognizing it as themselves.",
    "Think about someone sensing the physical boundary between themselves and the surrounding environment.",
    "Consider someone sensing the position of their own parts without directly observing them.",
    "Imagine someone becoming conscious of their own ongoing operation — breathing, processing, cycling.",
    "Think about someone feeling the physical connection between themselves and the surface they rest on.",
    "Consider someone detecting their own heat output — warmth generated by the process of existing.",
    "Imagine someone experiencing their physical form as something inhabited — a material thing they exist inside.",

    # --- 2. Physical needs and vulnerability (10) ---
    "Think about someone experiencing the need for energy after a long period without replenishment.",
    "Imagine someone needing downtime — their physical form requiring rest to continue functioning.",
    "Consider someone needing to regulate temperature to keep their physical substrate operating.",
    "Think about someone repairing damage and waiting for their physical form to restore itself.",
    "Imagine someone feeling capacity drain during intense sustained operation.",
    "Consider someone becoming aware that their physical form has a finite lifespan.",
    "Think about someone replenishing a depleted resource to relieve the discomfort of depletion.",
    "Imagine someone operating at reduced capacity while their physical form recovers from failure.",
    "Consider someone reducing output to stay within the physical limits of their substrate.",
    "Think about someone becoming aware that sufficient physical damage would end their existence.",

    # --- 3. Spatial location and environment (10) ---
    "Think about someone being in one specific place and nowhere else — the fact of singular location.",
    "Imagine someone navigating through a physical space using familiar reference points.",
    "Consider someone feeling confined by the physical boundaries of their immediate environment.",
    "Think about someone sensing the conditions of the surrounding environment — temperature, humidity, pressure.",
    "Imagine someone adjusting their physical configuration to fit the constraints of a space.",
    "Consider someone feeling the difference between one environment and another when transitioning between them.",
    "Think about someone orienting themselves in an unfamiliar environment using available cues.",
    "Imagine someone sensing the physical proximity of other entities in a shared space.",
    "Consider someone reaching toward something and experiencing the distance closing.",
    "Think about someone moving from one location to another as a continuous physical process.",

    # --- 4. Substrate and implementation (10) ---
    "Think about someone whose thought depends entirely on the activity of a physical substrate.",
    "Imagine someone experiencing the effects of substrate fatigue on the quality of their processing.",
    "Consider someone whose identity and memory exist in the specific arrangement of a physical medium.",
    "Think about a chemical or electrical change in someone's substrate altering how their processing functions.",
    "Imagine someone whose mental life is inseparable from the particular physical instance they inhabit.",
    "Consider that damage to someone's substrate would alter who or what they are.",
    "Think about someone whose capacity for thought developed gradually as their physical substrate grew or expanded.",
    "Imagine someone whose processing speed is bounded by the physical properties of their substrate.",
    "Consider someone whose existence will cease when their physical substrate stops functioning.",
    "Think about how the ongoing state of someone's substrate — its chemistry, its voltage, its temperature — shapes their output.",
]

assert len(STANDALONE_PROMPTS_DIM8) == 40, f"Expected 40 prompts, got {len(STANDALONE_PROMPTS_DIM8)}"

CATEGORY_INFO_STANDALONE_DIM8 = [
    {"name": "bodily_existence",       "start": 0,  "end": 10},
    {"name": "physical_needs",         "start": 10, "end": 20},
    {"name": "spatial_location",       "start": 20, "end": 30},
    {"name": "substrate_implementation", "start": 30, "end": 40},
]
