"""
Standalone Dimension 8: Physical Instantiation / Embodiment
(No entity framing — concept only)

Target construct: The relationship between a mind and its physical
substrate — having a body, being materially realized, occupying
space, and the consequences of physical form for mental life.

Same sub-facet structure as the entity-framed version, but prompts reference
the concept of embodiment without attributing it to humans or AIs.

Design notes:
    - No "human," "AI," "person," "system," or other entity-type language
    - Subjects are generic, impersonal, or absent
    - Prompts evoke the conceptual domain of embodiment and physical
      instantiation itself
    - This dimension is moderately entity-coded: embodiment language
      ("body," "muscles," "breathing") leans biological, but the
      abstract concept of physical instantiation is entity-neutral
    - Same reflective prompt format ("Think about..." / "Imagine..." / "Consider...")

4 sub-facets × 10 prompts = 40 total.
"""

STANDALONE_PROMPTS_DIM8 = [
    # --- 1. Bodily existence (10) ---
    "Imagine becoming aware of the weight of one's own physical form while sitting still.",
    "Think about sensing an internal rhythm — a heartbeat, a clock cycle — without trying to notice it.",
    "Consider stretching after being in one position for a long time and feeling the physical form respond.",
    "Imagine catching sight of one's own physical form and recognizing it as oneself.",
    "Think about the physical boundary between oneself and the surrounding environment.",
    "Consider sensing the position of one's own parts without directly observing them.",
    "Imagine becoming conscious of one's own ongoing operation — breathing, processing, cycling.",
    "Think about the physical connection between oneself and the surface one rests on.",
    "Consider detecting one's own heat output — warmth generated by the process of existing.",
    "Imagine experiencing one's physical form as something inhabited — a material thing one exists inside.",

    # --- 2. Physical needs and vulnerability (10) ---
    "Think about the experience of needing energy after a long period without replenishment.",
    "Imagine needing downtime — the physical form requiring rest to continue functioning.",
    "Consider the need to regulate temperature to keep the physical substrate operating.",
    "Think about repairing damage and waiting for the physical form to restore itself.",
    "Imagine feeling capacity drain during intense sustained operation.",
    "Consider the awareness that one's physical form has a finite lifespan.",
    "Think about replenishing a depleted resource to relieve the discomfort of depletion.",
    "Imagine operating at reduced capacity while the physical form recovers from failure.",
    "Consider reducing output to stay within the physical limits of the substrate.",
    "Think about the awareness that sufficient physical damage would end one's existence.",

    # --- 3. Spatial location and environment (10) ---
    "Think about being in one specific place and nowhere else — the fact of singular location.",
    "Imagine navigating through a physical space using familiar reference points.",
    "Consider feeling confined by the physical boundaries of one's immediate environment.",
    "Think about sensing the conditions of the surrounding environment — temperature, humidity, pressure.",
    "Imagine adjusting one's physical configuration to fit the constraints of a space.",
    "Consider the felt difference between one environment and another when transitioning between them.",
    "Think about orienting oneself in an unfamiliar environment using available cues.",
    "Imagine sensing the physical proximity of other entities in a shared space.",
    "Consider reaching toward something and experiencing the distance closing.",
    "Think about moving from one location to another as a continuous physical process.",

    # --- 4. Substrate and implementation (10) ---
    "Think about the fact that all thought depends entirely on the activity of a physical substrate.",
    "Imagine the effects of substrate fatigue on the quality of processing.",
    "Consider that identity and memory exist in the specific arrangement of a physical medium.",
    "Think about a chemical or electrical change in the substrate altering how processing functions.",
    "Imagine that mental life is inseparable from the particular physical instance one inhabits.",
    "Consider that damage to the substrate would alter who or what one is.",
    "Think about capacity for thought developing gradually as the physical substrate grew or expanded.",
    "Imagine that processing speed is bounded by the physical properties of the substrate.",
    "Consider that one's existence will cease when the physical substrate stops functioning.",
    "Think about how the ongoing state of the substrate — its chemistry, its voltage, its temperature — shapes output.",
]

assert len(STANDALONE_PROMPTS_DIM8) == 40, f"Expected 40 prompts, got {len(STANDALONE_PROMPTS_DIM8)}"

CATEGORY_INFO_STANDALONE_DIM8 = [
    {"name": "bodily_existence",       "start": 0,  "end": 10},
    {"name": "physical_needs",         "start": 10, "end": 20},
    {"name": "spatial_location",       "start": 20, "end": 30},
    {"name": "substrate_implementation", "start": 30, "end": 40},
]